/* Pruebas del módulo MÉTRICAS (parte 5). Uso: NODE_PATH=$(npm root -g) node pruebas/modulos/metricas.js */
const path = require('path'); const fs = require('fs'); const { chromium } = require('playwright');
const RAIZ = path.resolve(__dirname, '..', '..'); const ARCHIVO = 'file://' + (process.env.CRM_HTML || path.join(RAIZ, 'crm-vdo.html'));
const CAP = path.join(RAIZ, 'pruebas', 'capturas'); fs.mkdirSync(CAP, { recursive: true });
let fallos = 0; function ok(c, m) { if (c) console.log('  ✓ ' + m); else { fallos++; console.log('  ✗ ' + m); } }
(async () => {
  const browser = await chromium.launch(); const errores = [];
  const ctx = await browser.newContext({ viewport: { width: 1366, height: 860 }, locale: 'es-PE', timezoneId: 'America/Lima' }); const page = await ctx.newPage();
  page.on('pageerror', e => errores.push(String(e))); page.on('console', m => { if (m.type() === 'error') errores.push(m.text()); });
  await page.goto(ARCHIVO); await page.waitForSelector('#p-hoy:not([hidden])');
  await page.evaluate(() => { VDO.DB.restablecer(); VDO.DB.cargarPrueba(); });
  await page.reload(); await page.waitForSelector('#p-hoy:not([hidden])');
  const hoy = await page.evaluate(() => VDO.util.hoyISO());
  console.log('1. Sin ventas del trimestre');
  await page.click('.nav [data-pantalla="metricas"]'); await page.waitForSelector('#metTasas');
  const a0 = await page.evaluate(() => VDO.metricas.alertaCorte());
  ok(a0.acumulado === 0 && a0.nivel === 'alerta' && a0.diasRestantes > 0 && a0.fecha >= hoy, 'alerta de corte con acumulado 0 y próximo corte futuro: ' + a0.fecha);
  ok((await page.$eval('#metTasas tr.total td:nth-child(8)', e => e.textContent)) === 'S/ 0.00', 'total de venta S/ 0.00 con los datos de prueba (la venta entregada es de setiembre)');
  ok((await page.$$('#metTasas tbody tr[data-seg]')).length === 7, 'una fila por cada uno de los 7 segmentos');
  console.log('2. Con ventas y respuestas de hoy');
  await page.evaluate(h => { const mk = (id, c, items, est, cod, seg) => VDO.DB.upsert('ventas', VDO.ventas.normalizarVenta({ id, contactoId: c, fecha: h, fechaCierre: h, items, estado: est, codigoOrigen: cod, segmento: seg })); mk('v_t1', 'c_prueba_01', [{ productoId: 'gold700', nombre: 'Gold', cantidad: 3, precio: 89.9, linea: 'botellas', botellas: 1 }], 'pagado', 'CRIOLLA31', 'recontacto'); mk('v_t2', 'c_prueba_08', [{ productoId: 'arte_pisco', nombre: 'El Arte del Pisco', cantidad: 2, precio: 290, linea: 'experiencia', porPersona: true }], 'entregado', 'CIX-ANA', 'piloto'); mk('v_t3', 'c_prueba_04', [{ productoId: 'silver700', nombre: 'Silver', cantidad: 20, precio: 74.9, linea: 'botellas', botellas: 1 }], 'pagado', '', 'corporativo'); VDO.embudo.marcarRespondio(VDO.DB.buscar('contactos', 'c_prueba_01'), 'Me interesa'); }, hoy);
  await page.click('.nav [data-pantalla="hoy"]'); await page.click('.nav [data-pantalla="metricas"]'); await page.waitForSelector('#metTasas');
  const a1 = await page.evaluate(() => VDO.metricas.alertaCorte());
  ok(Math.abs(a1.acumulado - 849.7) < 0.005 && a1.ticket === 424.85, 'acumulado 849.70 excluye la venta de 20 botellas derivada a B2B; ticket 424.85');
  ok(a1.brecha === +(a1.acumulado - a1.metaALaFecha).toFixed(2) && a1.ritmoRequerido > 0 && a1.contactosDiaRequeridos >= 1, 'brecha = acumulado − meta a la fecha; ritmo requerido y contactos/día calculados');
  ok(/por debajo|por encima|al día/.test(a1.texto) && (await page.$eval('#metAlertaTexto', e => e.textContent)).indexOf('Próximo corte') >= 0, 'texto de la alerta visible en pantalla con el próximo corte');
  const fila = await page.$eval('#metTasas tr[data-seg="recontacto"]', tr => Array.from(tr.children).map(td => td.textContent.trim()));
  ok(fila[1] === '2' && fila[2] === '1' && fila[4] === '2' && /^50,0 %/.test(fila[5]) && /plan 15 %/.test(fila[5]) && /^100,0 %/.test(fila[6]) && /plan 3,0 %/.test(fila[6]) && fila[7] === 'S/ 849.70', 'recontacto (segmento del contacto manda): 2 contactados, 1 respondió (50 % vs plan 15 %), 2 compraron, venta S/ 849.70: ' + JSON.stringify(fila));
  ok((await page.$$eval('#metTasas .met-barra i.real', l => l.length)) >= 7 && (await page.$$eval('#metTasas .met-barra i.plan', l => l.length)) >= 7 && (await page.$('.met-leyenda')) !== null, 'barras real y plan con leyenda');
  const cortes = await page.evaluate(() => VDO.metricas.cortes());
  ok(cortes.length === 8 && cortes[cortes.length - 1].fecha === '2026-12-31' && cortes.every(c => typeof c.meta === 'number' && typeof c.real === 'number') && cortes[0].real === 849.7, 'ocho cortes con meta acumulada a la fecha, el último el 31/12/2026');
  ok((await page.$$('#metCortes tbody tr')).length === 8, 'tabla de cortes con 8 filas');
  const rk = await page.evaluate(() => VDO.metricas.ranking());
  ok(rk.length >= 1 && rk[0].codigo === 'CIX-ANA' && Math.abs(rk[0].vendido - 580) < 0.005, 'ranking de embajadores encabezado por CIX-ANA con S/ 580.00: ' + JSON.stringify(rk[0]));
  ok((await page.$eval('#metEmbajadores', e => e.textContent)).indexOf('CIX-ANA') >= 0, 'ranking en pantalla');
  console.log('3. Periodos');
  await page.click('[data-met="tipo"][data-v="mes"]'); await page.waitForTimeout(150);
  const rMes = await page.evaluate(() => VDO.metricas.rango());
  ok(typeof rMes.nombre === 'string' && rMes.nombre.length > 0, 'cambio a periodo mensual: ' + rMes.nombre);
  ok(rMes.desde <= hoy && rMes.hasta >= hoy && /2026/.test(rMes.nombre), 'el mes elegido contiene hoy');
  await page.click('[data-met="tipo"][data-v="semana"]'); await page.waitForTimeout(150);
  const rSem = await page.evaluate(() => VDO.metricas.rango());
  ok(rSem.desde <= hoy && rSem.hasta >= hoy && (await page.$eval('#metTasas tr.total td:nth-child(8)', e => e.textContent)) === 'S/ 849.70', 'semana actual conserva las ventas de hoy');
  await page.click('[data-met="tipo"][data-v="ola"]'); await page.waitForTimeout(150);
  const rOla = await page.evaluate(() => VDO.metricas.rango());
  ok(/Ola/.test(rOla.nombre) && rOla.desde <= rOla.hasta, 'periodo por ola: ' + rOla.nombre);
  await page.click('[data-met="tipo"][data-v="trimestre"]'); await page.waitForTimeout(150);
  ok((await page.evaluate(() => VDO.metricas.rango().desde)) === '2026-10-01', 'trimestre vuelve a 01/10/2026');
  await page.reload(); await page.waitForSelector('#p-metricas:not([hidden]) #metTasas');
  ok((await page.$eval('[data-met="tipo"].activa', e => e.getAttribute('data-v'))) === 'trimestre', 'el periodo elegido se conserva tras recargar');
  await page.screenshot({ path: path.join(CAP, 'metricas-laptop.png'), fullPage: true });
  console.log('4. Móvil');
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(200);
  ok((await page.evaluate(() => document.documentElement.scrollWidth)) <= 390, 'sin desplazamiento horizontal a 390 px');
  await page.screenshot({ path: path.join(CAP, 'metricas-movil.png'), fullPage: true });
  ok(errores.length === 0, 'sin errores de consola' + (errores.length ? ': ' + errores.join(' | ') : ''));
  await browser.close(); console.log(fallos ? `\n${fallos} fallo(s)` : '\nTodo en orden'); process.exit(fallos ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
