/* Pruebas del módulo PIPELINE (parte 3). Uso: NODE_PATH=$(npm root -g) node pruebas/modulos/pipeline.js */
const path = require('path'); const fs = require('fs'); const { chromium } = require('playwright');
const RAIZ = path.resolve(__dirname, '..', '..'); const ARCHIVO = 'file://' + (process.env.CRM_HTML || path.join(RAIZ, 'crm-vdo.html'));
const CAP = path.join(RAIZ, 'pruebas', 'capturas'); fs.mkdirSync(CAP, { recursive: true });
let fallos = 0; function ok(c, m) { if (c) console.log('  ✓ ' + m); else { fallos++; console.log('  ✗ ' + m); } }
(async () => {
  const browser = await chromium.launch(); const errores = [];
  const ctx = await browser.newContext({ viewport: { width: 1366, height: 860 }, locale: 'es-PE', timezoneId: 'America/Lima' }); const page = await ctx.newPage();
  page.on('pageerror', e => errores.push(String(e))); page.on('console', m => { if (m.type() === 'error') errores.push(m.text()); });
  await page.goto(ARCHIVO); await page.waitForSelector('#p-hoy:not([hidden])');
  await page.evaluate(() => { VDO.DB.restablecer(); VDO.DB.cargarPrueba(); });
  await page.reload(); await page.waitForSelector('#p-hoy:not([hidden])');
  console.log('1. Kanban de personas');
  await page.click('.nav [data-pantalla="pipeline"]'); await page.waitForSelector('#pipeTablero');
  const cols = await page.$$eval('#pipeTablero .pipe-col', els => els.map(e => ({ etapa: e.getAttribute('data-etapa'), n: e.querySelectorAll('.pipe-card').length })));
  ok(cols.length === 6 && cols.map(c => c.etapa).join(',') === 'atraer,iniciar,calificar,proponer,cerrar,fidelizar', 'seis columnas en orden del embudo');
  ok(cols.reduce((s, c) => s + c.n, 0) === 8 && cols[0].n === 3 && cols[5].n === 1, 'ocho tarjetas repartidas (3 en Atraer, 1 en Fidelizar): ' + JSON.stringify(cols.map(c => c.n)));
  const conteo = await page.$eval('#pipeConteo', e => e.textContent); ok(/8 activos/.test(conteo), 'conteo de activos: ' + conteo);
  await page.screenshot({ path: path.join(CAP, 'pipeline-laptop.png'), fullPage: true });
  await page.selectOption('.pipe-filtros select[name="segmento"]', 'breca'); await page.waitForTimeout(100);
  ok((await page.$$('#pipeTablero .pipe-card')).length === 1, 'filtro por segmento deja una tarjeta');
  await page.selectOption('.pipe-filtros select[name="segmento"]', ''); await page.waitForTimeout(100);
  await page.check('.pipe-filtros input[name="vencidos"]'); await page.waitForTimeout(100);
  const vencidosEsperados = await page.evaluate(() => { var hoy = VDO.util.hoyISO(); return VDO.DB.tabla('contactos').filter(c => c.estado === 'activo' && c.proximoToque && c.proximoToque < hoy).length; });
  ok((await page.$$('#pipeTablero .pipe-card')).length === vencidosEsperados && vencidosEsperados >= 2, 'filtro de vencidos deja solo las tarjetas con próximo toque anterior a hoy (' + vencidosEsperados + ')');
  await page.uncheck('.pipe-filtros input[name="vencidos"]'); await page.waitForTimeout(100);
  console.log('2. Mover de etapa');
  await page.click('.pipe-card[data-id="c_prueba_02"] [data-pipe="mover"][data-dir="1"]'); await page.waitForTimeout(100);
  ok((await page.evaluate(() => VDO.DB.buscar('contactos', 'c_prueba_02').etapa)) === 'iniciar', 'botón ▶ mueve a Iniciar en la base');
  ok(!!(await page.$('.pipe-col[data-etapa="iniciar"] .pipe-card[data-id="c_prueba_02"]')), 'la tarjeta se reubica en la columna Iniciar');
  const disabled = await page.$eval('.pipe-col[data-etapa="atraer"] .pipe-card [data-pipe="mover"][data-dir="-1"]', b => b.disabled); ok(disabled, 'en Atraer el botón ◀ está deshabilitado');
  const drop = await page.evaluate(() => { const card = document.querySelector('.pipe-card[data-id="c_prueba_02"]'); const col = document.querySelector('.pipe-col[data-etapa="calificar"]'); const dt = new DataTransfer(); card.dispatchEvent(new DragEvent('dragstart', { bubbles: true, dataTransfer: dt })); col.dispatchEvent(new DragEvent('dragover', { bubbles: true, dataTransfer: dt, cancelable: true })); col.dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: dt, cancelable: true })); return VDO.DB.buscar('contactos', 'c_prueba_02').etapa; });
  ok(drop === 'calificar', 'arrastrar y soltar mueve a Calificar');
  console.log('3. Fuera del embudo');
  await page.evaluate(() => { const c = VDO.DB.buscar('contactos', 'c_prueba_03'); VDO.embudo.marcarDormido(c, 'prueba'); });
  await page.click('.nav [data-pantalla="pipeline"]'); await page.waitForSelector('#pipeTablero');
  ok(/1 dormidos/.test(await page.$eval('#pipeConteo', e => e.textContent)), 'el dormido se cuenta fuera del embudo');
  await page.click('.pipe-otros summary'); await page.waitForTimeout(100);
  await page.click('.pipe-otros [data-pipe="reactivar"][data-id="c_prueba_03"]'); await page.waitForTimeout(100);
  ok((await page.evaluate(() => { const c = VDO.DB.buscar('contactos', 'c_prueba_03'); return c.estado === 'activo' && c.proximoToque === VDO.util.hoyISO(); })), 'reactivar devuelve al embudo con toque hoy');
  console.log('4. Ficha del contacto');
  await page.click('.pipe-card[data-id="c_prueba_06"] [data-pipe="ficha"]'); await page.waitForSelector('.pipe-ficha');
  const ficha = await page.evaluate(() => ({ nombre: document.querySelector('.pipe-ficha h3').textContent, actual: document.querySelector('.pipe-paso.actual').textContent, inter: document.querySelectorAll('.pipe-ficha-sec .pipe-lista li').length, cuenta: !!document.querySelector('[data-f="cuenta"]') }));
  ok(ficha.nombre === 'Renzo Castillo' && ficha.actual === 'Proponer' && ficha.inter >= 2 && ficha.cuenta, 'ficha con embudo, interacciones, ventas y cuenta: ' + JSON.stringify(ficha));
  await page.selectOption('select[data-f="etapa"]', 'cerrar'); await page.waitForTimeout(150);
  ok((await page.evaluate(() => VDO.DB.buscar('contactos', 'c_prueba_06').etapa)) === 'cerrar', 'mover etapa desde la ficha');
  await page.screenshot({ path: path.join(CAP, 'pipeline-ficha-laptop.png'), fullPage: true });
  await page.keyboard.press('Escape');
  await page.click('.nav [data-pantalla="contactos"]'); await page.waitForSelector('#p-contactos table');
  await page.click('#p-contactos tr[data-id="c_prueba_01"] td:first-child b'); await page.waitForSelector('.pipe-ficha');
  ok((await page.$eval('.pipe-ficha h3', e => e.textContent)) === 'María Fernanda Rojas', 'la ficha abre desde Contactos al tocar el nombre');
  await page.keyboard.press('Escape');
  console.log('5. Cuentas y eventos');
  await page.click('.nav [data-pantalla="pipeline"]'); await page.waitForSelector('#pipeTablero');
  await page.click('[data-pipe="tab"][data-tab="cuentas"]'); await page.waitForSelector('.pipe-filtros-cuentas');
  const kcols = await page.$$eval('#pipeTablero .pipe-col', els => els.map(e => e.querySelectorAll('.pipe-card').length));
  ok(kcols.length === 6 && kcols.reduce((s, n) => s + n, 0) === 2, 'dos cuentas de prueba en seis columnas de estado');
  await page.click('[data-pipe="nueva-cuenta"]'); await page.waitForSelector('#formCuenta');
  await page.fill('#formCuenta [name="empresa"]', 'Gestión Humana · fiesta de fin de año');
  await page.selectOption('#formCuenta [name="segmento"]', 'grupos');
  await page.fill('#cuentaBuscar', 'Patricia'); await page.waitForSelector('#cuentaSug [data-elegir]'); await page.click('#cuentaSug [data-elegir]');
  ok((await page.$$('#cuentaChips .pipe-chip-contacto')).length === 1, 'contacto existente agregado como chip');
  await page.click('#cuentaNuevoBtn'); await page.fill('#nuevoNombre', 'Lorena Paz'); await page.fill('#nuevoTel', '911 000 222'); await page.fill('#nuevoCargo', 'Gerente de RR. HH.'); await page.click('#nuevoCrear'); await page.waitForTimeout(100);
  ok((await page.$$('#cuentaChips .pipe-chip-contacto')).length === 2 && (await page.evaluate(() => { const c = VDO.DB.tabla('contactos').filter(x => x.nombre === 'Lorena Paz')[0]; return c && c.telefono === '+51911000222' && c.segmento === 'grupos' && c.empresa.indexOf('Gestión Humana') === 0; })), 'contacto nuevo creado y agregado');
  await page.selectOption('#formCuenta [name="paquete"]', 'coctelero'); await page.fill('#formCuenta [name="personas"]', '25'); await page.click('#cuentaSugerir');
  ok((await page.$eval('#formCuenta [name="monto"]', e => e.value)) === '8580', 'monto sugerido: Coctelero para 25 personas = S/ 8,580');
  await page.fill('#formCuenta [name="proximoPaso"]', 'Enviar propuesta'); await page.fill('#formCuenta [name="fechaProximoPaso"]', '2026-10-09'); await page.fill('#formCuenta [name="fechaEvento"]', '2026-12-18');
  await page.click('#formCuenta button[type="submit"]'); await page.waitForTimeout(150);
  const k = await page.evaluate(() => VDO.DB.tabla('cuentas').filter(x => x.empresa.indexOf('Gestión Humana') === 0)[0]);
  ok(k && k.contactos.length === 2 && k.monto === 8580 && k.estado === 'contactado' && k.fechaEvento === '2026-12-18', 'cuenta guardada con contactos, monto y fechas');
  await page.click('.pipe-card[data-cuenta="' + k.id + '"] [data-pipe="mover-cuenta"][data-dir="1"]'); await page.waitForTimeout(100);
  ok((await page.evaluate(id => VDO.DB.buscar('cuentas', id).estado, k.id)) === 'respondio', 'mover cuenta a Respondió');
  await page.click('.pipe-card[data-cuenta="' + k.id + '"] [data-pipe="venta-cuenta"]'); await page.waitForSelector('#formVenta');
  ok(!!(await page.$('#formVenta')), '"Venta" desde la cuenta abre el formulario de venta'); await page.keyboard.press('Escape');
  await page.screenshot({ path: path.join(CAP, 'pipeline-cuentas-laptop.png'), fullPage: true });
  console.log('6. Celular');
  const movil = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, locale: 'es-PE', timezoneId: 'America/Lima' }); const pm = await movil.newPage(); pm.on('pageerror', e => errores.push('móvil: ' + e));
  await pm.goto(ARCHIVO); await pm.waitForSelector('#p-hoy:not([hidden])'); await pm.click('.tabbar-movil [data-pantalla="pipeline"]'); await pm.waitForSelector('#pipeTablero');
  ok(!(await pm.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)), 'sin desplazamiento horizontal de la página en celular');
  ok((await pm.$$('.pipe-tabs-movil .btn')).length === 6, 'pestañas de columnas visibles en celular');
  await pm.screenshot({ path: path.join(CAP, 'pipeline-celular.png'), fullPage: true });
  ok(errores.length === 0, 'sin errores de consola' + (errores.length ? ': ' + errores.join(' | ') : ''));
  await browser.close(); console.log(fallos ? '\nFALLOS: ' + fallos : '\nTodo en orden.'); process.exit(fallos ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
