/* Pruebas del módulo PLANTILLAS (parte 5). Uso: NODE_PATH=$(npm root -g) node pruebas/modulos/plantillas.js */
const path = require('path'); const fs = require('fs'); const { chromium } = require('playwright');
const RAIZ = path.resolve(__dirname, '..', '..'); const ARCHIVO = 'file://' + (process.env.CRM_HTML || path.join(RAIZ, 'crm-vdo.html'));
const CAP = path.join(RAIZ, 'pruebas', 'capturas'); fs.mkdirSync(CAP, { recursive: true });
let fallos = 0; function ok(c, m) { if (c) console.log('  ✓ ' + m); else { fallos++; console.log('  ✗ ' + m); } }
(async () => {
  const browser = await chromium.launch(); const errores = [];
  const ctx = await browser.newContext({ viewport: { width: 1366, height: 860 }, locale: 'es-PE', timezoneId: 'America/Lima' }); const page = await ctx.newPage();
  page.on('pageerror', e => errores.push(String(e))); page.on('console', m => { if (m.type() === 'error') errores.push(m.text()); });
  page.on('dialog', d => d.accept());
  await page.goto(ARCHIVO); await page.waitForSelector('#p-hoy:not([hidden])');
  await page.evaluate(() => { VDO.DB.restablecer(); VDO.DB.cargarPrueba(); });
  await page.reload(); await page.waitForSelector('#p-hoy:not([hidden])');
  console.log('1. Biblioteca y filtros');
  await page.click('.nav [data-pantalla="plantillas"]'); await page.waitForSelector('#plLista');
  const total = await page.evaluate(() => VDO_DATOS.PLANTILLAS.length);
  ok((await page.$eval('#plConteo', e => e.textContent)) === total + ' de ' + total && (await page.$$('#plLista .pl-item')).length === total, 'las ' + total + ' plantillas del plan precargadas');
  await page.selectOption('.pl-filtros select[name="canal"]', 'correo'); await page.waitForTimeout(150);
  const nCorreo = await page.evaluate(() => VDO.DB.tabla('plantillas').filter(p => p.canal === 'correo').length);
  ok((await page.$$('#plLista .pl-item')).length === nCorreo && nCorreo > 0, 'filtro por canal correo: ' + nCorreo);
  await page.selectOption('.pl-filtros select[name="canal"]', ''); await page.waitForTimeout(150);
  await page.fill('.pl-filtros input[name="texto"]', 'breca'); await page.waitForTimeout(400);
  const nBreca = await page.$$('#plLista .pl-item');
  ok(nBreca.length > 0 && nBreca.length < total && (await page.evaluate(() => document.activeElement.name === 'texto')), 'búsqueda por texto filtra y conserva el foco: ' + nBreca.length);
  await page.fill('.pl-filtros input[name="texto"]', ''); await page.waitForTimeout(400);
  console.log('2. Editor con vista previa');
  await page.click('[data-pl="nueva"]'); await page.waitForSelector('#plForm');
  await page.fill('#plForm [name="nombre"]', 'Prueba saludo'); await page.selectOption('#plForm [name="segmento"]', 'boca');
  await page.fill('#plForm [name="texto"]', 'Hola {nombre}, te escribe Joaquín de {empresa}. Tu código es {codigo}. {variableRara}'); await page.waitForTimeout(100);
  ok(/Variables desconocidas: \{variableRara\}/.test(await page.$eval('#plAviso', e => e.textContent)), 'aviso de variable desconocida');
  await page.selectOption('#plContacto', 'c_prueba_01'); await page.waitForTimeout(100);
  const previa = await page.$eval('#plPrevia', e => e.textContent);
  ok(/Hola María,/.test(previa) && /de G2 Alta\./.test(previa) && /MFR-07/.test(previa) && !/\{nombre\}/.test(previa), 'vista previa rellena {nombre} (primer nombre), {empresa} del contacto y {codigo}: ' + previa.slice(0, 80));
  await page.click('#plForm [data-var="ocasion"]'); await page.waitForTimeout(50);
  ok(/\{ocasion\}/.test(await page.$eval('#plForm [name="texto"]', e => e.value)), 'el botón de variable inserta {ocasion} en el texto');
  await page.check('#plForm [name="masivo"]'); await page.waitForTimeout(100);
  ok(/exceso es dañino/.test(await page.$eval('#plPrevia', e => e.textContent)) && /menores de 18/.test(await page.$eval('#plPrevia', e => e.textContent)), 'marcar masivo agrega las dos leyendas legales a la vista previa');
  await page.selectOption('#plForm [name="canal"]', 'correo'); await page.waitForTimeout(100);
  ok(!(await page.$eval('#plAsuntoCampo', e => e.hidden)), 'canal correo muestra el campo Asunto');
  await page.fill('#plForm [name="asunto"]', 'Un pisco para {nombre}');
  await page.click('#plForm button[type="submit"]'); await page.waitForTimeout(250);
  const nueva = await page.evaluate(() => VDO.DB.tabla('plantillas').find(p => p.nombre === 'Prueba saludo'));
  ok(nueva && nueva.segmento === 'boca' && nueva.canal === 'correo' && nueva.masivo === true && nueva.asunto === 'Un pisco para {nombre}' && (await page.$eval('#plConteo', e => e.textContent)) === (total + 1) + ' de ' + (total + 1), 'plantilla guardada con sus campos y el contador sube a ' + (total + 1));
  console.log('3. Probar, duplicar, activar, eliminar');
  const id = nueva.id;
  await page.click(`[data-pl="probar"][data-id="${id}"]`); await page.waitForSelector('#plPrevia');
  await page.selectOption('#plContacto', 'c_prueba_02'); await page.waitForTimeout(100);
  const wa = await page.$eval('#plWa', a => ({ hidden: a.hidden, href: a.href }));
  ok(!wa.hidden && /^https:\/\/wa\.me\/51\d+\?text=/.test(wa.href) && decodeURIComponent(wa.href).indexOf('Hola ') > 0, 'Probar arma el enlace wa.me con el texto rellenado');
  await page.click('[data-plm="cerrar"]'); await page.waitForTimeout(100);
  await page.click(`[data-pl="duplicar"][data-id="${id}"]`); await page.waitForTimeout(200);
  ok((await page.evaluate(() => VDO.DB.tabla('plantillas').filter(p => /^Prueba saludo/.test(p.nombre)).length)) === 2, 'Duplicar crea una copia');
  await page.click(`[data-pl="activar"][data-id="${id}"]`); await page.waitForTimeout(200);
  ok((await page.evaluate(i => VDO.DB.buscar('plantillas', i).activa, id)) === false && (await page.$eval(`.pl-item[data-id="${id}"]`, e => e.classList.contains('inactiva'))), 'Desactivar marca la plantilla inactiva');
  await page.selectOption('.pl-filtros select[name="activa"]', 'no'); await page.waitForTimeout(150);
  ok((await page.$$('#plLista .pl-item')).length === 1, 'filtro de inactivas muestra solo esa');
  await page.selectOption('.pl-filtros select[name="activa"]', ''); await page.waitForTimeout(150);
  await page.click(`[data-pl="editar"][data-id="${id}"]`); await page.waitForSelector('#plForm');
  await page.click('[data-plm="eliminar"]'); await page.waitForTimeout(200);
  ok(!(await page.evaluate(i => VDO.DB.buscar('plantillas', i), id)), 'Eliminar borra la plantilla');
  console.log('4. Restaurar e importar');
  const primera = await page.evaluate(() => { const p = VDO.DB.tabla('plantillas')[0]; p.texto = 'texto cambiado'; VDO.DB.upsert('plantillas', p); return p.id; });
  await page.click('[data-pl="restaurar"]'); await page.waitForSelector('#modalContenido [data-accion="ok"]'); await page.click('#modalContenido [data-accion="ok"]'); await page.waitForTimeout(250);
  ok((await page.evaluate(i => VDO.DB.buscar('plantillas', i).texto, primera)) !== 'texto cambiado' && (await page.evaluate(() => VDO.DB.tabla('plantillas').filter(p => /^Prueba saludo/.test(p.nombre)).length)) === 1, 'Restaurar repone el texto del plan y conserva la copia creada por el usuario');
  await page.evaluate(() => VDO.plantillas.importar(JSON.stringify({ plantillas: [{ id: 'pl_imp_x', nombre: 'Importada', segmento: 'pyme', toque: 2, texto: 'Hola {nombre}' }, { nombre: 'sin texto' }] })));
  await page.waitForTimeout(150);
  ok((await page.evaluate(() => { const p = VDO.DB.buscar('plantillas', 'pl_imp_x'); return p && p.canal === 'whatsapp' && p.activa === true && p.segmento === 'pyme'; })) && !(await page.evaluate(() => VDO.DB.tabla('plantillas').some(p => p.nombre === 'sin texto'))), 'importar JSON completa valores por defecto y descarta entradas sin texto');
  ok((await page.evaluate(() => VDO.plantillas.variablesDesconocidas('{nombre} {x} {codigo} {y}').join(','))) === 'x,y', 'variablesDesconocidas detecta solo las que no existen');
  await page.screenshot({ path: path.join(CAP, 'plantillas-laptop.png'), fullPage: true });
  console.log('5. Móvil');
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(200);
  ok((await page.evaluate(() => document.documentElement.scrollWidth)) <= 390, 'sin desplazamiento horizontal a 390 px');
  await page.click('[data-pl="nueva"]'); await page.waitForSelector('#plForm'); await page.waitForTimeout(150);
  ok((await page.evaluate(() => document.documentElement.scrollWidth)) <= 390, 'editor en móvil sin desplazamiento horizontal');
  await page.screenshot({ path: path.join(CAP, 'plantillas-editor-movil.png'), fullPage: true });
  ok(errores.length === 0, 'sin errores de consola' + (errores.length ? ': ' + errores.join(' | ') : ''));
  await browser.close(); console.log(fallos ? `\n${fallos} fallo(s)` : '\nTodo en orden'); process.exit(fallos ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
