/* Pruebas del módulo REPORTE SEMANAL (parte 5). Uso: NODE_PATH=$(npm root -g) node pruebas/modulos/reporte.js */
const path = require('path'); const fs = require('fs'); const { chromium } = require('playwright');
const RAIZ = path.resolve(__dirname, '..', '..'); const ARCHIVO = 'file://' + (process.env.CRM_HTML || path.join(RAIZ, 'crm-vdo.html'));
const CAP = path.join(RAIZ, 'pruebas', 'capturas'); fs.mkdirSync(CAP, { recursive: true });
let fallos = 0; function ok(c, m) { if (c) console.log('  ✓ ' + m); else { fallos++; console.log('  ✗ ' + m); } }
(async () => {
  const browser = await chromium.launch(); const errores = [];
  const ctx = await browser.newContext({ viewport: { width: 1366, height: 860 }, locale: 'es-PE', timezoneId: 'America/Lima' }); const page = await ctx.newPage();
  page.on('pageerror', e => errores.push(String(e))); page.on('console', m => { if (m.type() === 'error') errores.push(m.text()); });
  await page.goto(ARCHIVO); await page.waitForSelector('#p-hoy:not([hidden])');
  await page.evaluate(() => { VDO.DB.restablecer(); VDO.DB.cargarPrueba(); });
  await page.reload(); await page.waitForSelector('#p-hoy:not([hidden])');
  const hoy = await page.evaluate(() => VDO.util.hoyISO());
  await page.evaluate(h => { const mk = (id, c, items, est, cod, seg) => VDO.DB.upsert('ventas', VDO.ventas.normalizarVenta({ id, contactoId: c, fecha: h, fechaCierre: h, items, estado: est, codigoOrigen: cod, segmento: seg })); mk('v_t1', 'c_prueba_01', [{ productoId: 'gold700', nombre: 'Gold', cantidad: 3, precio: 89.9, linea: 'botellas', botellas: 1 }], 'pagado', 'CRIOLLA31', 'recontacto'); mk('v_t2', 'c_prueba_08', [{ productoId: 'arte_pisco', nombre: 'El Arte del Pisco', cantidad: 2, precio: 290, linea: 'experiencia', porPersona: true }], 'entregado', 'CIX-ANA', 'piloto'); mk('v_t3', 'c_prueba_04', [{ productoId: 'silver700', nombre: 'Silver', cantidad: 20, precio: 74.9, linea: 'botellas', botellas: 1 }], 'pagado', '', 'corporativo'); }, hoy);
  console.log('1. Texto del reporte');
  await page.click('.nav [data-pantalla="reporte"]'); await page.waitForSelector('#repTexto');
  const t = await page.$eval('#repTexto', e => e.textContent);
  ok(/^REPORTE SEMANAL B2C · semana del \d\d\/\d\d\/2026 al \d\d\/\d\d\/2026 · Joaquín Díaz/.test(t), 'encabezado con la semana y el responsable');
  ok(/1\. VENTAS DE LA SEMANA/.test(t) && /2\. AVANCE DEL TRIMESTRE/.test(t) && /3\. ACTIVIDAD DE LA SEMANA/.test(t) && /4\./.test(t) && /5\./.test(t) && /6\./.test(t), 'seis secciones numeradas');
  ok(/Total: 2 ventas · S\/ 849\.70 · ticket promedio S\/ 424\.85/.test(t), 'ventas de la semana: 2 ventas, S/ 849.70, ticket 424.85');
  ok(/Mix: botellas S\/ 269\.70 \(32 %\) · experiencia S\/ 580\.00 \(68 %\) · objetivo 60 % \/ 40 %/.test(t), 'mix botellas/experiencias con el objetivo 60/40');
  ok(/Derivadas a B2B \(no suman\): 1 · S\/ 1,498\.00/.test(t), 'la venta de 20 botellas aparece como derivada a B2B y no suma');
  ok(/CIX-ANA: 1 venta · S\/ 580\.00/.test(t) && /CRIOLLA31: 1 venta · S\/ 269\.70/.test(t), 'ventas por código de origen');
  ok(/Acumulado: S\/ 849\.70 · cuota oficial acumulada S\/ [\d,]+\.\d\d \([\d,]+ %\) · proyección acumulada/.test(t) && /Para cerrar el trimestre en S\/ 200,000\.00/.test(t), 'avance del trimestre contra cuota y proyección, ritmo para S/ 200,000');
  ok(/Tasas por segmento \(real vs plan\)/.test(t) && /Recontacto WhatsApp Business: 2 contactados/.test(t), 'tasas por segmento de la semana');
  const gen = await page.evaluate(l => VDO.reporte.generar(l), '2026-09-07');
  ok(/semana del 07\/09\/2026 al 12\/09\/2026/.test(gen) && /Total: 1 venta[s]? · S\/ /.test(gen) === /Total: 1 venta/.test(gen), 'generar() para otra semana arma el texto de esa semana: ' + gen.split('\n')[0]);
  console.log('2. Navegación de semanas, correo y descargas');
  const sub0 = await page.$eval('#p-reporte .sub', e => e.textContent);
  await page.click('[data-rep="semana"][data-v="-7"]'); await page.waitForTimeout(150);
  const sub1 = await page.$eval('#p-reporte .sub', e => e.textContent);
  ok(sub1 !== sub0 && !/S\/ 849\.70 · ticket/.test(await page.$eval('#repTexto', e => e.textContent)), 'semana anterior cambia el periodo y ya no incluye las ventas de hoy');
  await page.click('[data-rep="hoy"]'); await page.waitForTimeout(150);
  ok((await page.$eval('#p-reporte .sub', e => e.textContent)) === sub0, 'volver a la semana actual');
  await page.fill('#repCorreo', 'comite@bvo.com.pe'); await page.waitForTimeout(100);
  const mail = await page.$eval('#repMail', a => a.href);
  ok(/^mailto:comite@bvo\.com\.pe\?subject=/.test(mail) && decodeURIComponent(mail).indexOf('REPORTE SEMANAL B2C') > 0, 'el enlace mailto lleva destinatario, asunto y el texto: ' + mail.slice(0, 60));
  await page.reload(); await page.waitForSelector('#p-reporte:not([hidden]) #repTexto');
  ok((await page.$eval('#repCorreo', e => e.value)) === 'comite@bvo.com.pe', 'el correo se conserva tras recargar');
  const [descarga] = await Promise.all([page.waitForEvent('download'), page.click('[data-rep="txt"]')]);
  ok(/^reporte-semanal-\d{4}-\d\d-\d\d\.txt$/.test(descarga.suggestedFilename()), 'descarga .txt: ' + descarga.suggestedFilename());
  console.log('3. Historial');
  await page.click('[data-rep="guardar"]'); await page.waitForTimeout(200);
  ok((await page.$$('.rep-hist li')).length === 1 && (await page.evaluate(() => VDO.DB.datos.ui.reportes.length)) === 1, 'guardar agrega al historial');
  await page.click('[data-rep="ver"][data-i="0"]'); await page.waitForSelector('#modalContenido .rep-texto');
  ok(/REPORTE SEMANAL B2C/.test(await page.$eval('#modalContenido .rep-texto', e => e.textContent)), 'Ver abre el reporte guardado');
  await page.click('#modalContenido [data-accion="cerrar"]'); await page.waitForTimeout(100);
  await page.evaluate(() => { for (let i = 0; i < 25; i++) VDO.DB.datos.ui.reportes.unshift({ semana: '2026-10-05', generado: VDO.util.ahoraISO(), texto: 'x' + i }); });
  await page.click('[data-rep="guardar"]'); await page.waitForTimeout(200);
  ok((await page.evaluate(() => VDO.DB.datos.ui.reportes.length)) === 20, 'el historial se recorta a 20');
  await page.click('[data-rep="borrar"][data-i="0"]'); await page.waitForTimeout(150);
  ok((await page.evaluate(() => VDO.DB.datos.ui.reportes.length)) === 19, 'borrar quita una entrada');
  await page.screenshot({ path: path.join(CAP, 'reporte-laptop.png'), fullPage: true });
  console.log('4. Móvil');
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(200);
  ok((await page.evaluate(() => document.documentElement.scrollWidth)) <= 390, 'sin desplazamiento horizontal a 390 px');
  await page.screenshot({ path: path.join(CAP, 'reporte-movil.png'), fullPage: true });
  ok(errores.length === 0, 'sin errores de consola' + (errores.length ? ': ' + errores.join(' | ') : ''));
  await browser.close(); console.log(fallos ? `\n${fallos} fallo(s)` : '\nTodo en orden'); process.exit(fallos ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
