/* Pruebas del módulo VENTAS (parte 4). Uso: NODE_PATH=$(npm root -g) node pruebas/modulos/ventas.js */
const path = require('path'); const fs = require('fs'); const { chromium } = require('playwright');
const RAIZ = path.resolve(__dirname, '..', '..'); const ARCHIVO = 'file://' + (process.env.CRM_HTML || path.join(RAIZ, 'crm-vdo.html'));
const CAP = path.join(RAIZ, 'pruebas', 'capturas'); fs.mkdirSync(CAP, { recursive: true });
let fallos = 0; function ok(c, m) { if (c) console.log('  ✓ ' + m); else { fallos++; console.log('  ✗ ' + m); } }
(async () => {
  const browser = await chromium.launch(); const errores = [];
  const ctx = await browser.newContext({ viewport: { width: 1366, height: 860 }, locale: 'es-PE', timezoneId: 'America/Lima' }); const page = await ctx.newPage();
  page.on('pageerror', e => errores.push(String(e))); page.on('console', m => { if (m.type() === 'error') errores.push(m.text()); });
  await page.goto(ARCHIVO); await page.waitForSelector('#p-hoy:not([hidden])');
  await page.evaluate(() => { VDO.DB.restablecer(); VDO.DB.cargarPrueba(); });
  await page.reload(); await page.waitForSelector('#p-hoy:not([hidden])');
  const hoy = await page.evaluate(() => VDO.util.hoyISO());
  console.log('1. Ventas · avance y tabla');
  await page.click('.nav [data-pantalla="ventas"]'); await page.waitForSelector('#ventasCuerpo');
  const acum = await page.$eval('#ventasAcumulado', e => e.textContent);
  ok(acum === 'S/ 0.00', 'acumulado del trimestre con los datos de prueba (la venta entregada es de setiembre): ' + acum);
  ok((await page.$$('#ventasCuerpo tr[data-id]')).length === 3, 'tabla con las tres ventas de prueba');
  await page.evaluate(h => { const v = VDO.ventas.normalizarVenta({ id: 'v_t1', contactoId: 'c_prueba_01', fecha: h, fechaCierre: h, items: [{ productoId: 'gold700', nombre: 'Gold', cantidad: 3, precio: 89.9, linea: 'botellas', botellas: 1 }], estado: 'pagado', codigoOrigen: 'CRIOLLA31', segmento: 'recontacto' }); VDO.DB.upsert('ventas', v); const e = VDO.ventas.normalizarVenta({ id: 'v_t2', contactoId: 'c_prueba_08', fecha: h, fechaCierre: h, items: [{ productoId: 'arte_pisco', nombre: 'El Arte del Pisco', cantidad: 2, precio: 290, linea: 'experiencia', porPersona: true }], estado: 'entregado', codigoOrigen: 'CIX-ANA', segmento: 'piloto' }); VDO.DB.upsert('ventas', e); const b = VDO.ventas.normalizarVenta({ id: 'v_t3', contactoId: 'c_prueba_04', fecha: h, fechaCierre: h, items: [{ productoId: 'silver700', nombre: 'Silver', cantidad: 20, precio: 74.9, linea: 'botellas', botellas: 1 }], estado: 'pagado', codigoOrigen: 'CORP-BCP', segmento: 'corporativo' }); VDO.DB.upsert('ventas', b); }, hoy);
  await page.click('.nav [data-pantalla="hoy"]'); await page.click('.nav [data-pantalla="ventas"]'); await page.waitForSelector('#ventasCuerpo');
  const k = await page.evaluate(() => ({ acum: document.getElementById('ventasAcumulado').textContent, b2b: document.getElementById('ventasB2B').textContent, bot: document.getElementById('ventasMixBotellas').textContent, exp: document.getElementById('ventasMixExperiencia').textContent, filas: document.querySelectorAll('#ventasCuerpo tr[data-id]').length }));
  ok(k.acum === 'S/ 849.70' && k.b2b === '1' && k.bot === 'S/ 269.70' && k.exp === 'S/ 580.00' && k.filas === 6, 'acumulado 269.70 + 580.00, la de 20 botellas va aparte como B2B: ' + JSON.stringify(k));
  await page.selectOption('.ventas-filtros select[name="estado"]', 'b2b'); await page.waitForTimeout(100);
  ok((await page.$$('#ventasCuerpo tr[data-id]')).length === 1, 'filtro de derivadas a B2B');
  await page.click('[data-vta="limpiar-filtros"]'); await page.waitForTimeout(100);
  await page.fill('.ventas-filtros input[name="texto"]', 'CRIOLLA'); await page.waitForTimeout(300);
  ok((await page.$$('#ventasCuerpo tr[data-id]')).length === 1 && (await page.evaluate(() => document.activeElement.name === 'texto')), 'búsqueda por código conserva el foco');
  await page.click('[data-vta="limpiar-filtros"]'); await page.waitForTimeout(100);
  await page.click('[data-vta="nueva-venta"]'); await page.waitForSelector('#formVenta');
  await page.fill('#formVenta [name="buscarContacto"]', 'Luis Alberto Paredes'); await page.selectOption('#formVenta .venta-item [data-item="productoId"]', 'blue710'); await page.selectOption('#formVenta [name="estado"]', 'pagado'); await page.click('#formVenta button[type="submit"]'); await page.waitForTimeout(200);
  ok((await page.$eval('#ventasAcumulado', e => e.textContent)) === 'S/ 1,249.60', 'registrar venta desde el botón suma al acumulado');
  await page.screenshot({ path: path.join(CAP, 'ventas-laptop.png'), fullPage: true });
  console.log('2. Calculadora de grupos');
  await page.click('[data-vta="pestana"][data-tab="calculadora"]'); await page.waitForSelector('#calcForm');
  await page.fill('#calcForm [name="personas"]', '30'); await page.selectOption('#calcForm [name="modo"]', 'paquete'); await page.selectOption('#calcForm [name="paquete"]', 'signature'); await page.waitForTimeout(100);
  ok((await page.$eval('#calcTotal', e => e.textContent)) === 'S/ 12,990.00', 'Signature para 30 personas = S/ 12,990.00');
  await page.fill('#calcForm [name="personas"]', '8'); await page.selectOption('#calcForm [name="modo"]', 'experiencia'); await page.selectOption('#calcForm [name="experiencia"]', 'arte_pisco'); await page.waitForTimeout(100);
  ok((await page.$eval('#calcTotal', e => e.textContent)) === 'S/ 2,320.00', 'El Arte del Pisco para 8 personas = S/ 2,320.00');
  await page.selectOption('#calcForm [name="breca"]', 'true'); await page.waitForTimeout(100);
  ok((await page.$eval('#calcTotal', e => e.textContent)) === 'S/ 1,740.00', 'con 25 % Breca = S/ 1,740.00');
  await page.click('[data-vta="calc-cotizar"]'); await page.waitForSelector('#formVenta');
  ok((await page.$eval('#ventaTotal', e => e.textContent)) === 'S/ 1,740.00' && !(await page.$('[data-eliminar-venta]')), 'Crear cotización abre el formulario con el total y sin botón Eliminar');
  await page.keyboard.press('Escape');
  await page.screenshot({ path: path.join(CAP, 'ventas-calculadora-laptop.png'), fullPage: true });
  console.log('3. Embajadores');
  await page.click('[data-vta="pestana"][data-tab="embajadores"]'); await page.waitForSelector('#embTabla');
  const fila = await page.$eval('#embTabla tr[data-id="e_prueba_01"]', tr => ({ pos: tr.getAttribute('data-pos'), vendido: tr.querySelector('[data-col="vendido"]').textContent, comision: tr.querySelector('[data-col="comision"]').textContent, saldo: tr.querySelector('[data-col="saldo"]').textContent }));
  ok(fila.pos === '1' && fila.vendido === 'S/ 580.00' && fila.comision === 'S/ 58.00' && fila.saldo === 'S/ 58.00', 'venta con código CIX-ANA atribuida a Ana Lucía con comisión del 10 %: ' + JSON.stringify(fila));
  await page.evaluate(h => { const v = VDO.ventas.normalizarVenta({ id: 'v_t4', contactoId: 'c_prueba_07', fecha: h, fechaCierre: h, items: [{ productoId: 'blue710', nombre: 'Blue', cantidad: 3, precio: 399.9, linea: 'botellas', botellas: 1 }], estado: 'pagado', codigoOrigen: 'cix-ana', segmento: 'piloto' }); VDO.DB.upsert('ventas', v); }, hoy);
  await page.click('[data-vta="pestana"][data-tab="embajadores"]'); await page.waitForSelector('#embTabla');
  const fila2 = await page.$eval('#embTabla tr[data-id="e_prueba_01"]', tr => ({ vendido: tr.querySelector('[data-col="vendido"]').textContent, comision: tr.querySelector('[data-col="comision"]').textContent }));
  ok(fila2.vendido === 'S/ 1,779.70' && fila2.comision === 'S/ 266.96', 'al superar S/ 1,500 en el mes la comisión del mes es 15 % (código en minúsculas también atribuye)');
  await page.click('#embTabla tr[data-id="e_prueba_01"] [data-vta="emb-detalle"]'); await page.waitForSelector('#formPago');
  await page.fill('#formPago [name="monto"]', '100'); await page.click('#formPago button[type="submit"]'); await page.waitForTimeout(150);
  ok((await page.$eval('#embSaldo', e => e.textContent)) === 'S/ 166.96', 'registrar un pago reduce el saldo');
  await page.keyboard.press('Escape');
  await page.click('[data-vta="emb-nuevo"]'); await page.waitForSelector('#formEmbajador');
  await page.fill('#formEmbajador [name="nombre"]', 'Ana María Soto'); await page.fill('#formEmbajador [name="ciudad"]', 'Chiclayo'); await page.waitForTimeout(50);
  ok((await page.$eval('#formEmbajador [name="codigo"]', e => e.value)) === 'CIX-ANA', 'sugiere el código CIX-ANA');
  await page.click('#formEmbajador button[type="submit"]'); await page.waitForTimeout(150);
  ok(!(await page.evaluate(() => document.getElementById('modal').hidden)) && (await page.evaluate(() => VDO.DB.tabla('embajadores').length)) === 2, 'código duplicado bloqueado');
  await page.fill('#formEmbajador [name="codigo"]', 'CIX-ANAM'); await page.click('#formEmbajador button[type="submit"]'); await page.waitForTimeout(150);
  ok((await page.evaluate(() => VDO.DB.tabla('embajadores').length)) === 3, 'embajador nuevo creado con otro código');
  await page.screenshot({ path: path.join(CAP, 'ventas-embajadores-laptop.png'), fullPage: true });
  console.log('4. Celular');
  const movil = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, locale: 'es-PE', timezoneId: 'America/Lima' }); const pm = await movil.newPage(); pm.on('pageerror', e => errores.push('móvil: ' + e));
  await pm.goto(ARCHIVO); await pm.waitForSelector('#p-hoy:not([hidden])'); await pm.click('.tabbar-movil [data-pantalla="ventas"]'); await pm.waitForSelector('#ventasCuerpo');
  ok(!(await pm.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)), 'sin desplazamiento horizontal en celular');
  await pm.screenshot({ path: path.join(CAP, 'ventas-celular.png'), fullPage: true });
  ok(errores.length === 0, 'sin errores de consola' + (errores.length ? ': ' + errores.join(' | ') : ''));
  await browser.close(); console.log(fallos ? '\nFALLOS: ' + fallos : '\nTodo en orden.'); process.exit(fallos ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
